# Generated by Django 5.2.9 on 2026-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('product_type', models.CharField(choices=[('TC', 'Естественные цвета (True Color)'), ('NDVI', 'NDVI'), ('NDWI', 'NDWI')], max_length=10)),
                ('preview_path', models.CharField(max_length=500)),
                ('product_path', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('tile', 'date', 'product_type')},
            },
        ),
    ]
